version: "3.7"
services:
  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  simple-store:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    restart: always
    ports:
      - "8080:8080"
