swagger: "2.0"
info:
  title: Simple Store API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /public/categories/:
    get:
      tags:
      - public/categories
      summary: Get All Categories
      description: get only the active categories
      operationId: CategoryPublicController.Get All Categories
      parameters:
      - in: query
        name: limit
        description: limit of this request
        type: integer
        format: int64
      - in: query
        name: page
        description: page of this request
        type: integer
        format: int64
      responses:
        "200":
          description: ""
        "403":
          description: ""
  /public/metadata/:
    get:
      tags:
      - public/metadata
      summary: get all metadata
      description: get all metadata
      operationId: MetadataPublicController.GetAll
      parameters:
      - in: query
        name: limit
        description: limit of this request
        type: integer
        format: int64
      - in: query
        name: page
        description: page of this request
        type: integer
        format: int64
      responses:
        "200":
          description: ""
        "403":
          description: ""
  /public/users/login:
    post:
      tags:
      - public/users
      summary: login
      description: login
      operationId: UserPublicController.Login
      parameters:
      - in: body
        name: params
        description: body of this request
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: ""
        "403":
          description: ""
  /public/users/register:
    post:
      tags:
      - public/users
      summary: register
      description: register
      operationId: UserPublicController.Register
      parameters:
      - in: body
        name: params
        description: body of this request
        required: true
        schema:
          $ref: '#/definitions/datatransfers.RegisterRequest'
      responses:
        "200":
          description: ""
        "403":
          description: ""
definitions:
  datatransfers.RegisterRequest:
    title: RegisterRequest
    type: object
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
  models.User:
    title: User
    type: object
    properties:
      createdAt:
        type: string
        format: datetime
      email:
        type: string
      id:
        type: integer
        format: int32
      password:
        type: string
      token:
        type: string
      updatedAt:
        type: string
        format: datetime
      username:
        type: string
tags:
- name: public/metadata
  description: |
    Operations about object
- name: public/categories
  description: |
    Operations about object
- name: public/users
  description: |
    Operations about object
